--Q1. whatt is the total revenue generated by male vs. female customers  
select gender,sum(purchase_amount) as revenue
from customer_behave
group by gender

--Q2. which customers used a discount but still spent more than the average perchase amount ?
select customer_id, purchase_amount
from customer_behave
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_behave)

--Q3. which are the top 5 products with the highest average review rating ?
select top 5 
	item_purchased,
	round(avg(review_rating),2) as "avg_rating"
from customer_behave 
group by item_purchased
order by avg(review_rating) desc

--Q4. compare the average purchase amounts between standard and express shopping. 
select 
	shipping_type,
	round(avg(purchase_amount),2) as "avg purchase_amt"
from customer_behave
where shipping_type in ('Express', 'Standard')
group by shipping_type 

--Q5. Do subscribed customers spent more? compare average spend and total revenue between subscribers and non-subscribers 
select 
	subscription_status,
	count(customer_id) as "total_customers",
	avg(purchase_amount) as "avg_spent",
	sum(purchase_amount) as "total_revenue"
from customer_behave
group by subscription_status
order by avg_spent, total_revenue asc

--Q5. which 5 products have the highest percentage of purchases with discount applied ?
select top 5  
	item_purchased,
	sum(100 * case when discount_applied	= 'yes' then 1 else 0 end)/count(*) as discount_rate
from customer_behave
group by item_purchased
order by discount_rate desc

--Q6. segment customers into New, returning and loyal based into their local number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'loyal'
	end as customer_segment
from customer_behave
)
select 
	customer_segment,
	count(*) as "Number of customers"
from customer_type
group by customer_segment
order by count(*) asc

--Q7. what are the top 3 most purchased products wothin each category ?
WITH item_count as(
select 
	category,
	item_purchased,
	count(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) desc) as item_rank
from customer_behave
group by category, item_purchased
)
select 
	item_rank,
	category,
	item_purchased,
	total_orders
from item_count
where item_rank <=3

--Q9. who customers are repeat buyers (more than 5 previous purchases) also likely to subscribe 
select 
	subscription_status,
	count(customer_id) as total_members
from customer_behave
where previous_purchases > 5
group by subscription_status

---Q10. what is the revenue cointribution of each age group?
select 
	age_group,
	sum(purchase_amount) as total_revenue
from customer_behave
group by age_group
order by total_revenue desc

select top 50 * from customer_behave